apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: release-cutover-mch-version-upgrade
  namespace: installer
spec:
  params:
    - name: source_version
      type: string
      description: "X.Y version of the source MCH Configuration."
    - name: dest_version
      type: string
      description: "X.Y version of the destination MCH Configuration."
    - name: mce_source_version
      type: string
      description: "X.Y version of the source MCE Configuration."
    - name: mce_dest_version
      type: string
      description: "X.Y version of the destination MCE Configuration."
    - name: product_prefix
      type: string
      default: "release"
      description: "Prefix for the product, typically either release or backplane for ACM and MCE respectively."
    - name: mch_repo
      type: string
      default: "stolostron/multiclusterhub-operator"
      description: "repo_name for the MCH repository."
  steps:
    - image: 'quay.io/gurnben/tekton-runner:latest'
      name: upgrade-install-version
      resources: {}
      script: |
        git clone https://github.com/stolostron/release-cutover-automation.git
        cd release-cutover-automation
        python3 scripts/mch-version-upgrade.py


